site_name: Galital documentation
copyright: Copyright &copy; 2021 Galital
repo_url: https://github.com/starkleytech/galital-docs

markdown_extensions:
  - toc:
      toc_depth: 3
theme:
  markdown_extensions:
  features:
    - toc.integrate
  name: material
  features:
  custom_dir: overrides
  logo: assets/galital-logo.png
  favicon: assets/galital-logo.png
  language: en
google_analytics:
  - UA-190563951-2
  - auto
  
plugins:
  - search
  - i18n:
      languages:
        fr: "Français"
        en: "English"
      default_language: 'en'

extra:
  # Default mkdocs-material alternate links for untranslated pages
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector
  alternate:
    - name: English
      link: ""
      lang: en

    - name: Français
      link: index.fr/
      lang: fr



 