site_name: Galital documentation
copyright: Copyright &copy; 2021 Galital
markdown_extensions:
  - toc:
      toc_depth: 3
theme:
  markdown_extensions:
  features:
    - toc.integrate
  name: material
  features:
  custom_dir: overrides
  logo: assets/galital-logo.png
  favicon: assets/galital-logo.png
  language: en
google_analytics:
  - UA-190563951-2
  - auto
  
extra:
  alternate:

    # Switch to English
    - name: English
      link: galital/en/
      lang: en

    # Switch to French
    - name: Français
      link: galital/fr/
      lang: fr
  