site_name: Galital documentation
copyright: Copyright &copy; 2021 Galital
theme:
  name: material
  custom_dir: overrides
  logo: assets/galital-logo.png
  favicon: assets/galital-logo.png
google_analytics:
  - UA-190563951-2
  - auto
  